apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdp-time
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dammyng/training-class.git'
    targetRevision: HEAD
    path: cdp-time
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true